// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sundial.proto

#include "sundial.pb.h"
#include "sundial.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* SundialRPC_method_names[] = {
  "/SundialRPC/contactRemote",
};

std::unique_ptr< SundialRPC::Stub> SundialRPC::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SundialRPC::Stub> stub(new SundialRPC::Stub(channel));
  return stub;
}

SundialRPC::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_contactRemote_(SundialRPC_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SundialRPC::Stub::contactRemote(::grpc::ClientContext* context, const ::SundialRequest& request, ::SundialResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_contactRemote_, context, request, response);
}

void SundialRPC::Stub::experimental_async::contactRemote(::grpc::ClientContext* context, const ::SundialRequest* request, ::SundialResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_contactRemote_, context, request, response, std::move(f));
}

void SundialRPC::Stub::experimental_async::contactRemote(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SundialResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_contactRemote_, context, request, response, std::move(f));
}

void SundialRPC::Stub::experimental_async::contactRemote(::grpc::ClientContext* context, const ::SundialRequest* request, ::SundialResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_contactRemote_, context, request, response, reactor);
}

void SundialRPC::Stub::experimental_async::contactRemote(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SundialResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_contactRemote_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SundialResponse>* SundialRPC::Stub::AsynccontactRemoteRaw(::grpc::ClientContext* context, const ::SundialRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::SundialResponse>::Create(channel_.get(), cq, rpcmethod_contactRemote_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::SundialResponse>* SundialRPC::Stub::PrepareAsynccontactRemoteRaw(::grpc::ClientContext* context, const ::SundialRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::SundialResponse>::Create(channel_.get(), cq, rpcmethod_contactRemote_, context, request, false);
}

SundialRPC::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SundialRPC_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SundialRPC::Service, ::SundialRequest, ::SundialResponse>(
          [](SundialRPC::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::SundialRequest* req,
             ::SundialResponse* resp) {
               return service->contactRemote(ctx, req, resp);
             }, this)));
}

SundialRPC::Service::~Service() {
}

::grpc::Status SundialRPC::Service::contactRemote(::grpc::ServerContext* context, const ::SundialRequest* request, ::SundialResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


